# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Use powerline
USE_POWERLINE="true"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-syntax-highlighting zsh-autosuggestions)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export GPG_TTY=$(tty)
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

alias vim="nvim"
alias cat="bat -pP"
unalias ls
alias ls="exa -a"
unalias ll
alias ll="exa -la"
unalias grep
alias grep="rg"
alias make="make -j"
alias find="fd"
export PATH="$PATH:/home/nate/.cargo/bin"
